### PR TITLE
Get selector from options (for jQuery 3)

### LINKED ISSUE #295: jQuery 3.0 support?
With jQuery 3.0 a click anywhere on the page initializes an empty Swipebox that can't be closed again. Seems like a compatibility issue. Will Swipebox support jQuery 3.0?

### PR DESCRIPTION
**Pull request by andrews05**
This change provides compatibility with jQuery 3 by changing the way Swipebox works with dynamic content. Swipebox is no longer dynamic by default as the "selector" jQuery property that it previously relied on has been removed in jQuery 3.

To make Swipebox work with dynamic content it must instead be initialised by passing the selector as an option, similar to Bootstrap's popovers/tooltips. **Only do this for dynamic content.**
``` js
$(document).swipebox({ selector: '.swipebox' });
```
**For non-dynamic uses, simply apply this PR and you're done. You do not need the `selector` option.** Dynamic content refers to galleries where images may be added or removed on the fly.

Fixes #295.

### CODE REVIEW

**Comment by samuelg0rd0n** [comment]
Any progress on this?

**Comment by 1MikeMakuch** [comment]
Works for me with jquery 3.2.1 👍

**Comment by AntonFix** [comment]
Help me, please.
I've tryed:

```
<script>
    $(document).swipebox({selector: '.swipebox'});
    $('#gallery').click(function (e) {
        e.preventDefault();
        $.swipebox([
            {href: 'img/gallery/gall-img1.jpg', title: 'My Caption'},
            {href: 'img/gallery/gall-img14.jpg', title: 'My Second Caption'}
        ]);
    });
</script>
```
`<a id="gallery" href="#">View gallery</a>`

But does not work.

Why, where is my fault?

**Comment by dylanjameswagner** [comment]
I haven't tried to set this, but perhaps it may be not having `class="swipebox"` on your `a` for the selector property.

**Comment by sebgmc** [comment]
I ended up adding this to my swipebox.min.js:

`[...] j.init=function(){j.settings=c.extend({},i,f)**,l=j.settings.selector**,c.isArray(e)? [...]`

This is the same as suggested in https://github.com/brutaldesign/swipebox/issues/295

**Comment by andrews05** [comment]
To use the minified version you will need to run grunt to regenerate the .min.js after applying this PR. You do not need fix 295, you probably don't need to use the `selector` option at all. I've edited the first post to clarify this.

**Comment by andrews05** [comment]
I've added the minified file to the PR.

**Comment by Josh979** [comment]
Works great on JQuery 3.2.1, Thanks for the fix!

**Comment by simonered** [comment]
merge please

**Comment by pwall27** [comment]
Merge please

**Comment by mfg92** [comment]
Works for me with JQuery 3.3.1 too

**Comment by brandy000** [comment]
Ok, for Jquery I´m just using:

$(document).swipebox({ selector: '.swipebox' });

Am I right?

**Comment by jjnxpct** [comment]
The PR works for me. It would be great to see this fix added to a new release of Swipbox. Is anyone on this?

**Comment by fabtho** [comment]
I use the version from here with https://github.com/mho79/swipebox/ works for me with jQuery  3.4.0. This version is also aviable as npm: https://www.jsdelivr.com/package/npm/jquery.swipebox

**Comment by spencerthayer** [comment]
So this is abandoned software eh?

**Comment by samuelg0rd0n** [comment]
@spencerthayer Yes, it looks like this repo has been abandoned.

**Pull request closed without merging**
