### PR TITLE
Added nextSlide and prevSlide Callbacks

### PR DESCRIPTION
**Pull request by manual63**
[#165](https://github.com/brutaldesign/swipebox/issues/165) 

I added callbacks for nextSlide and prevSlide. I tested the code and it works well. The prevSlide and nextSlide methods could do other things if needed. I personally want to use them for logging analytics to see if and how the slideshow is used.

### CODE REVIEW

**Comment by micschk** [comment]
I need to use these callbacks as well. Any reason this patch doesn't seem to have been merged?

**Comment by manual63** [comment]
This was the first time I added something on GitHub and my IDE changed the
tabbing on all the code. So they didn't want to use it.

Look at my code. The callbacks were pretty easy to add. When I have time I
should do a pull of latest and add it these back in without reformatting
the code.

Shad

**Comment by micschk** [comment]
I re-applied your edits and sent a new PR

Thx!

**Comment by manual63** [comment]
Awesome

**Pull request closed without merging**
