### PR TITLE
allow an addtional image caption

### PR DESCRIPTION
**Pull request by splitbrain**
The attribute for title and caption are now configurable via the option array. A caption is usful to give an additional image description or provide proper attribution. This includes the XSS fix from #268

### CODE REVIEW

**Comment by splitbrain** [comment]
The demo has been adjusted to easily try it.

**Comment by brutaldesign** [comment]
Hi,

Seems .useful
But I can't merge your PR now, can you please resubmit from the actual version?

Cheers

**Comment by splitbrain** [comment]
I merged the current master and fixed the (minor) conflict.

**Comment by jjnxpct** [comment]
Hi! I was looking for the option to add the title or alt of the image to the pop-up image. I guess this PR makers this possible? I am just not sure wat 'PR' is and if this is already included in the current version of the plugin or do I have to download a different version somehow? Or do I need to change files manually?

What I would likt to do is use the alt or title tag of the 'original' image / thumbnail as a caption on the popup version. Can this be done? 

Thanks!

Kind regards,
Jip

**Comment by maxim-kukushkin** [comment]
Hi! I was looking so much for this simple feature. Sometimes family photos can have extra multi-line comments, which would be awesome to show in the bar. It's a shame that this PR could never be merged.
I have very limited version of JS, but may be I'll try to redo the code changes with the latest version. Just can't guarantee that I'll succeed with it

**Comment by maxim-kukushkin** [comment]
Raised a new PR, replicating the changes there: https://github.com/brutaldesign/swipebox/pull/392

**Pull request closed without merging**
