### PR TITLE
Added parameters to open and close callbacks

### PR DESCRIPTION
**Pull request by chris-kobrzak**
afterOpen and afterClose callbacks now have access to the current
target jQuery object.  This is useful if you need to know which image was clicked
to open the gallery and which image was viewed when users decided to
close the gallery, respectively.

The minified version of the JavaScript file (``jquery.swipebox.min.js``) 
has been created using the Grunt task supplied in the project.

Sample usage:
```javascript
$(".swipebox").swipebox({
  afterClose: function( imageNode ) {
    if ( imageNode === undefined ) {
      return;
    }
    // your code goes here
    // ...
  }
});
```

### CODE REVIEW

**Comment by matteocontrini** [comment]
Up

**Comment by matteocontrini** [comment]
Closed why?

**Comment by chris-kobrzak** [comment]
@brutaldesign, do you mind giving us some feedback as to why you thought this PR should be closed?
Many thanks!

**Comment by brutaldesign** [comment]
Hi,

I made a big mess with the PRs and last update.. some PR was ahead of
others and I made some changes as well so I just closed all PR.
I love this project but unfortunately I don't have may time to manage it

But the afterOpen and afterClose callbacks are good. I will add it to the
next update or just resubmit your PR

Sorry again

2015-06-26 14:41 GMT+02:00 Chris <notifications@github.com>:

> @brutaldesign <https://github.com/brutaldesign>, do you mind giving us
> some feedback as to why you thought this PR should be closed?
> Many thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brutaldesign/swipebox/pull/196#issuecomment-115666011>
> .
>



-- 
*Constantin Saguin*

**Comment by chris-kobrzak** [comment]
No worries, cheers for the update!

**Comment by matteocontrini** [comment]
Hey, an update on this?

**Pull request closed without merging**
